
export const ADD_WORKFLOW = 'ADD_WORKFLOW'
export const FILTER_WORKFLOW = 'FILTER_WORKFLOW'
export const DELETE_WORKFLOW = 'DELETE_WORKFLOW'
export const EDIT_WORKFLOW_STATUS = 'EDIT_WORKFLOW_STATUS'
export const CHANGE_WORKFLOW_STATUS = 'CHANGE_WORKFLOW_STATUS'
export const EDIT_WORKFLOW_TITLE = 'EDIT_WORKFLOW_TITLE'
export const SET_PENDING_WORKFLOW = 'SET_PENDING_WORKFLOW'

export const ADD_FIRST_NODE = 'ADD_FIRST_NODE';
export const SET_CURRENT_NODE = 'SET_CURRENT_NODE';
export const SHUFFLE_NODE = 'SHUFFLE_NODE'
export const DELETE_LAST_NODE = 'DELETE_LAST_NODE'
export const DELETE_NODE = 'DELETE_NODE'
export const ADD_NODE = 'ADD_NODE'
export const SAVE_NODE = 'SAVE_NODE'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const EDIT_FLOW_TITLE = 'EDIT_FLOW_TITLE'
export const EDIT_NODE_TITLE = 'EDIT_NODE_TITLE'
export const EDIT_NODE_CONTENT = 'EDIT_NODE_CONTENT'
export const CLEAR_SELECTED_NODE = 'CLEAR_SELECTED_NODE';